"""opportunities table

Revision ID: 555c621bc1a1
Revises: 1c31122413e8
Create Date: 2019-10-19 16:50:58.635868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555c621bc1a1'
down_revision = '1c31122413e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('estimated_time', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_description'), 'opportunity', ['description'], unique=False)
    op.create_index(op.f('ix_opportunity_estimated_time'), 'opportunity', ['estimated_time'], unique=False)
    op.create_index(op.f('ix_opportunity_location'), 'opportunity', ['location'], unique=False)
    op.create_index(op.f('ix_opportunity_timestamp'), 'opportunity', ['timestamp'], unique=False)
    op.create_index(op.f('ix_opportunity_type'), 'opportunity', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_type'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_timestamp'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_location'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_estimated_time'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_description'), table_name='opportunity')
    op.drop_table('opportunity')
    # ### end Alembic commands ###
